log_level = "warn"
position = "Top"

[appearance]
font_name = "JetBrainsMono Nerd Font"
opacity = 0.8

[appearance.menu]
opacity = 0.8

[modules]
left = [ "Workspaces" ]
center = [ "Clock" ]
right = [ [ "Tray", "SystemInfo", "Settings" ] ]

[workspaces]
visibility_mode = "All"
enable_workspace_filling = true
max_workspaces = 5

[settings]
indicators = ["Bluetooth", "Network", "Audio"]
bluetooth_more_cmd = "bluetui"
remove_airplane_btn = true
remove_idle_btn = true
shutdown_cmd = "systemctl poweroff"
